version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "lodolai/maintainers"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "lodolai/maintainers"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker):"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "lodolai/maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(actions):"
      include: "scope"
